### ISSUE TITLE
Readme.md 에 오타가 있습니다.

### ISSUE THREAD

**Issue by RektPunk** [WooilJeong/PyKakao#1]
즐겁게 보고 있습니다 :)
아래 Readme에 오타가 있는 것 같아서 이슈 남겨요.
https://github.com/WooilJeong/PyKakao/blob/bdd4451c41a14b436a93ebff6ff9ad2e24e3be7d/README.md?plain=1#L118

**Comment by WooilJeong** [comment]
@RektPunk 님 이슈 남겨주셔서 감사합니다. 문서 수정했습니다. :)
